-- MPRH_Variables.lua

local addonName, ns = ...

ns.EXPANSION = "The War Within"

ns.SEASON = "Season 2"

ns.SEASON_MAX_KEYSTONE_LEVEL = 12

ns.END_OF_DUNGEON_ITEM_LEVEL = {
    639,
    639,
    642,
    645,
    649,
    649,
    652,
    652,
    655,
    655,
    655,
}

ns.GREAT_VAULT_ITEM_LEVEL = {
    649,
    649,
    652,
    652,
    655,
    658,
    658,
    658,
    662,
    662,
    662,
}

ns.UPGRADE_CREST_AWARD = {
    "Runed Harbinger Crest",
    "Gilded Harbinger Crest",
}

ns.UPGRADE_CREST_QUANTITY = {
    10,
    12,
    14,
    16,
    18,
    20,
}

ns.UPGRADE_TRACK_COLOR = {
    champion = ITEM_QUALITY_COLORS[3], -- Rare (Champion)
    hero = ITEM_QUALITY_COLORS[4],     -- Epic (Hero)
    mythic = ITEM_QUALITY_COLORS[5],   -- Legendary (Mythic)
}

ns.MPRH_DATA = {
    { ns.END_OF_DUNGEON_ITEM_LEVEL[1],  ns.UPGRADE_TRACK_COLOR.champion, ns.UPGRADE_CREST_AWARD[1], ns.UPGRADE_CREST_QUANTITY[1], ns.GREAT_VAULT_ITEM_LEVEL[1],  ns.UPGRADE_TRACK_COLOR.hero },   -- +2
    { ns.END_OF_DUNGEON_ITEM_LEVEL[2],  ns.UPGRADE_TRACK_COLOR.champion, ns.UPGRADE_CREST_AWARD[1], ns.UPGRADE_CREST_QUANTITY[2], ns.GREAT_VAULT_ITEM_LEVEL[2],  ns.UPGRADE_TRACK_COLOR.hero },   -- +3
    { ns.END_OF_DUNGEON_ITEM_LEVEL[3],  ns.UPGRADE_TRACK_COLOR.champion, ns.UPGRADE_CREST_AWARD[1], ns.UPGRADE_CREST_QUANTITY[3], ns.GREAT_VAULT_ITEM_LEVEL[3],  ns.UPGRADE_TRACK_COLOR.hero },   -- +4
    { ns.END_OF_DUNGEON_ITEM_LEVEL[4],  ns.UPGRADE_TRACK_COLOR.champion, ns.UPGRADE_CREST_AWARD[1], ns.UPGRADE_CREST_QUANTITY[4], ns.GREAT_VAULT_ITEM_LEVEL[4],  ns.UPGRADE_TRACK_COLOR.hero },   -- +5
    { ns.END_OF_DUNGEON_ITEM_LEVEL[5],  ns.UPGRADE_TRACK_COLOR.hero,     ns.UPGRADE_CREST_AWARD[1], ns.UPGRADE_CREST_QUANTITY[5], ns.GREAT_VAULT_ITEM_LEVEL[5],  ns.UPGRADE_TRACK_COLOR.hero },   -- +6
    { ns.END_OF_DUNGEON_ITEM_LEVEL[6],  ns.UPGRADE_TRACK_COLOR.hero,     ns.UPGRADE_CREST_AWARD[2], ns.UPGRADE_CREST_QUANTITY[1], ns.GREAT_VAULT_ITEM_LEVEL[6],  ns.UPGRADE_TRACK_COLOR.hero },   -- +7
    { ns.END_OF_DUNGEON_ITEM_LEVEL[7],  ns.UPGRADE_TRACK_COLOR.hero,     ns.UPGRADE_CREST_AWARD[2], ns.UPGRADE_CREST_QUANTITY[2], ns.GREAT_VAULT_ITEM_LEVEL[7],  ns.UPGRADE_TRACK_COLOR.hero },   -- +8
    { ns.END_OF_DUNGEON_ITEM_LEVEL[8],  ns.UPGRADE_TRACK_COLOR.hero,     ns.UPGRADE_CREST_AWARD[2], ns.UPGRADE_CREST_QUANTITY[3], ns.GREAT_VAULT_ITEM_LEVEL[8],  ns.UPGRADE_TRACK_COLOR.hero },   -- +9
    { ns.END_OF_DUNGEON_ITEM_LEVEL[9],  ns.UPGRADE_TRACK_COLOR.hero,     ns.UPGRADE_CREST_AWARD[2], ns.UPGRADE_CREST_QUANTITY[4], ns.GREAT_VAULT_ITEM_LEVEL[9],  ns.UPGRADE_TRACK_COLOR.mythic }, -- +10
    { ns.END_OF_DUNGEON_ITEM_LEVEL[10], ns.UPGRADE_TRACK_COLOR.hero,     ns.UPGRADE_CREST_AWARD[2], ns.UPGRADE_CREST_QUANTITY[5], ns.GREAT_VAULT_ITEM_LEVEL[10], ns.UPGRADE_TRACK_COLOR.mythic }, -- +11
    { ns.END_OF_DUNGEON_ITEM_LEVEL[11], ns.UPGRADE_TRACK_COLOR.hero,     ns.UPGRADE_CREST_AWARD[2], ns.UPGRADE_CREST_QUANTITY[6], ns.GREAT_VAULT_ITEM_LEVEL[11], ns.UPGRADE_TRACK_COLOR.mythic }, -- +12
}
